image: stackstate/stackstate-agent-runner-circle:tracejava_base

stages:
  - prepare
  - build
  - test

variables:
  RESTORE_CACHE_ATTEMPTS: 2

.default_test_job: &default_test_job
  stage: test
  script:
    - echo Applying test task $TEST_TASK
    - GRADLE_OPTS="-Ddatadog.forkedMaxHeapSize=4G -Ddatadog.forkedMinHeapSize=64M" ./gradlew $TEST_TASK --build-cache --parallel --stacktrace --no-daemon --max-workers=6
  artifacts:
    paths:
      - ./reports/*
  after_script:
    - .circleci/collect_results_gitlab.sh
    - .circleci/collect_reports.sh

before_script:
  - export GRADLE_USER_HOME=$PWD/.gradle
  - mkdir -p $PWD/.gradle


clear_build_cache:
  stage: prepare
  before_script: []
  cache:
    policy: push
    key: "build-$CI_COMMIT_REF_SLUG"
    paths:
      - vendor
      - venv
  when: manual
  script:
    - rm -rf $GRADLE_USER_HOME/caches/*
    - rm -rf $GRADLE_USER_HOME/wrapper/*
    - rm -rf $GRADLE_USER_HOME/build-cache/*

build:
  stage: build
  variables:
    TEST_TASK: 'test latestDepTest jacocoTestReport jacocoTestCoverageVerification'
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - GRADLE_OPTS="-Dorg.gradle.jvmargs='-Xmx1G -Xms64M' -Ddatadog.forkedMaxHeapSize=1G -Ddatadog.forkedMinHeapSize=64M" ./gradlew clean :dd-java-agent:shadowJar compileTestGroovy compileLatestDepTestGroovy compileTestScala compileLatestDepTestScala compileTestJava compileLatestDepTestJava --build-cache --parallel --stacktrace --no-daemon --max-workers=8
    - ls -la ./build/libs/
#    - GRADLE_OPTS="-Ddatadog.forkedMaxHeapSize=4G -Ddatadog.forkedMinHeapSize=64M" ./gradlew $TEST_TASK --build-cache --parallel --stacktrace --no-daemon --max-workers=6
  after_script:
    - .circleci/collect_results_gitlab.sh
  cache:
    key: "build-$CI_COMMIT_REF_SLUG"
    paths:
      - $GRADLE_USER_HOME/caches/
      - $GRADLE_USER_HOME/wrapper/
      - $GRADLE_USER_HOME/build-cache/
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test_7:
  <<: *default_test_job
  variables:
     TEST_TASK: testJava7

test_8:
  <<: *default_test_job
  variables:
    # We are building on Java8, this is our default JVM so no need to set more homes
     TEST_TASK: test latestDepTest jacocoTestReport jacocoTestCoverageVerification

test_ibm8:
  <<: *default_test_job
  variables:
    TEST_TASK: testJavaIBM8

test_9:
  <<: *default_test_job
  variables:
    TEST_TASK: testJava9

test_10:
  <<: *default_test_job
  variables:
     TEST_TASK: testJava10

test_11:
  <<: *default_test_job
  variables:
     TEST_TASK: testJava11
